### ISSUE TITLE
Mistake in the FullGaussian2d readout

### ISSUE THREAD

**Issue by mohammadbashiri** [sinzlab/neuralpredictors#154]
The way we are sampling readout positions in [FullGaussian2d](https://github.com/sinzlab/neuralpredictors/blob/7f1b3039aeccf04633a52fc32b54889a767c32f6/neuralpredictors/layers/readouts/gaussian.py#L208) readout is different from what is claimed in the paper and also does not guarantee a proper Gaussian distribution (i.e. the learned covariance matrix is neither guaranteed to be symmetric nor have a positive determinant). More details below. 

The mistake is two-fold:

#### 1. The learned sigma is not restricted to be a proper covariance matrix.
Firstly, at initialization, we are [sampling the entries of the covariance matrix from a uniform distribution](https://github.com/sinzlab/neuralpredictors/blob/7f1b3039aeccf04633a52fc32b54889a767c32f6/neuralpredictors/layers/readouts/gaussian.py#L462). which means that it is possible to have covariances bigger than the variances, and there is no guarantee that the matrix is symmetric. Also, even if the initialization works out by chance (which is very unlikely), there is no restriction during learning.

As a result, we can end up with covariance matrices with negative determinants, which should not happen.

#### 2. the way we are using the sigma in the re-parametrization trick is not correct.
Our goal is to sample from a normal distribution with mean `\mu` and covariance `\sigma`. Instead, we are utilizing the reparametrization trick, but the way we are doing it **is not correct**. [What we do](https://github.com/sinzlab/neuralpredictors/blob/7f1b3039aeccf04633a52fc32b54889a767c32f6/neuralpredictors/layers/readouts/gaussian.py#L423-L427) is to transform the samples from a standard normal distribution with the covariance matrix `\sigma @ sample_{std_normal} + \mu`, but this is NOT equivalent to sampling from the normal distribution with mean `\mu` and covariance matrix `\sigma`.

@fabiansinz would you agree with these points? or am I missing something?

If my understanding is correct, my suggestion for a fix is as follows:
- learn a rotation angle `\theta` and two eigenvalues (variances) `s` per neuron 
- then `\sigma = rot_mat(\theta) @ diag(s) @ rot_mat(\theta).T`
- sample via `rot_mat(\theta) @ diag(sqrt(s)) @ sample_{std_normal}`

This way we would have a proper covariance matrix, the sampling is correct, and instead of 4 parameters per neuron, we would have 3 parameters to learn.

**Comment by fabiansinz** [comment]
I think the model is correct. `sigma` is simply not the covariance matrix, but `sigma.T @ sigma` is (which is also pd and symmetric). So it's a misnomer. The parametrization over rotation angles and eigenvalues might save a parameter, but I have the -- unproven -- hunch that it's not nice to optimize. The normal reparametrization trick doesn't care about that either. I don't think that the extra parameter matters.

**Comment by mohammadbashiri** [comment]
Thanks for the explanation. TODO: remove the clamping line.

**Comment by mohammadbashiri** [comment]
Addressed in https://github.com/sinzlab/neuralpredictors/pull/155.
