### ISSUE TITLE
Wrong order of dimensions for readout in_shape

### ISSUE THREAD

**Issue by KonstantinWilleke** [sinzlab/neuralpredictors#175]
When we pass the shape of the core output tensor to the readout, we consistently have the wrong order of `height` and `width`.

```
c, w, h = in_shape
```
(from https://github.com/sinzlab/neuralpredictors/blob/711ffeeead468aaca0c0b9dac0cc66419f7faa83/neuralpredictors/layers/readouts/gaussian.py#L64)

it's not a bug per se, because it is consistent internally. But would be clean to change it for all readouts.

**Comment by MaxFBurg** [comment]
Should be same as what is commonly used in pytorch, i.e. (batch, channel, height, width), right?

**Comment by pollytur** [comment]
Solved in #225
