### ISSUE TITLE
Bug report - stride does not change for RotationEquivariant2dCore

### ISSUE THREAD

**Issue by pollytur** [sinzlab/neuralpredictors#176]
I tried to change the stride for  RotationEquivariant2dCore, while it does not updates (checked with `model.stride`).
To reproduce: 
```
model = RotationEquivariant2dCore(..., stride=2)
print(model.stride) # should print 1
```

The issue I guess is that stride gets reinitialised by the default value during calling the` super.__init__` as stride is not passed there ([source code link](https://github.com/sinzlab/neuralpredictors/blob/main/neuralpredictors/layers/cores/conv2d.py#L378)).

The dirty fix (for someone who need it urgently) could be 

```
self.num_rotations = num_rotations
self.upsampling = upsampling
self.rot_eq_batch_norm = rot_eq_batch_norm
self.init_std = init_std
super().__init__(*args, **kwargs, input_regularizer=input_regularizer, stride=stride)
```

 or stride could also passes as a part of kwargs in further versions of the lib

**Comment by mohammadbashiri** [comment]
Right. Any shared arg between `RotationEquivariant2dCore` and `Stacked2dCore` should be passed when calling `super().__init__()` and as far as I checked stride was the only one.

I think your suggestion is good. Alternatively, you could just remove it from the `RotationEquivariant2dCore` init args and also attributes - then it will be part of the `kwargs`. I would also suggest just calling the super in the beginning and then setting the other attributes. Would you mind creating a PR for this @pollytur?

**Comment by pollytur** [comment]
Sure, I can make a PR for this with passing the argument then (like stated above if its fine)

As for calling the super in the beginning and then setting the other attributes - it will not work correctly without passing the stride as well as it initiates the network architecture with [add_subsequent_layers](https://github.com/sinzlab/neuralpredictors/blob/a761c1efa41c57eaea50075a6d7e4a56e74d1ca2/neuralpredictors/layers/cores/conv2d.py#L196), which already uses [stride](https://github.com/sinzlab/neuralpredictors/blob/a761c1efa41c57eaea50075a6d7e4a56e74d1ca2/neuralpredictors/layers/cores/conv2d.py#L263) and changing stride after `super.__init__()`  will not change the architecture
