### ISSUE TITLE
PR issues

### ISSUE THREAD

**Issue by pollytur** [sinzlab/neuralpredictors#185]
@cblessing24 
Dear Christoph, 
I am not sure what happened during PR testing. From what I get into logs, no tests failed but there are also no tests for this lines and the checks want me to do them. Is it correct / necessary or am I missing something?

[PR link](https://github.com/sinzlab/neuralpredictors/pull/184)

Thanks in advance! 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/49938348/205350620-def8b51a-a99c-4f36-9f38-3e7bd99b6ef3.png">

**Comment by cblessing24** [comment]
These last two checks are failing because the code you added is not covered by tests. You can either write tests for that code (which would be great!) or you can ignore them because they are not required for merging the pull request.
