### ISSUE TITLE
Redesign the device_state to work with individual devices

### ISSUE THREAD

**Issue by KonstantinWilleke** [sinzlab/neuralpredictors#93]
As of now, the device state 
https://github.com/sinzlab/neuralpredictors/blob/5d06b38120f8bf61e746cd66ce940a496e3c9354/neuralpredictors/training.py#L87
only works with `cuda` or `cpu` as an input. For tmulti GPU training, it should be able to handle the actual devices on top of these inputs.

**Comment by eywalker** [comment]
This is partially addressed by #94

**Comment by pollytur** [comment]
@KonstantinWilleke 
But we generally do not support multi-GPU training so far, no? (also `BatchNorm` should be replaces with `SyncBatchNorm` in such a case)

**Comment by pollytur** [comment]
[this issue is closed as it is not in the agenda to implement multi-gpu support soon]
